### PR TITLE
#166790079 set heroku to deploy

### PR DESCRIPTION
**Pull request by kagabof**
#### What does this PR do?
 - setting up Heroku
#### Description of Task to be completed?
 - added profile for Heroku to run the app.
- Added add script in the package.json for Heroku to run.
- added a production database in config.json.
#### How should this be manually tested?
 - by deploying on Heroku.
#### Any background context you want to provide?
 - N/A
#### What are the relevant pivotal tracker stories?
[166790079](https://www.pivotaltracker.com/story/show/166790079)
#### Screenshots (if appropriate)
 
Screen Shot 2019-06-27 at 11 15 14

#### Questions:
 - N/A

### CODE REVIEW

**Review by pngabo — CHANGES_REQUESTED** [review]
Can you please add relevant pivotal tracker stories.

**Comment by shaluchandwani** [comment]
Please change the PR description according to the format.

**Review by Joe-Joseph — COMMENTED** [review]
I'm not sure how I can test this, may be you can add an API that sends a welcome message and send us a Heroku link so that we may be able to test it in postman. and let's make sure that we are creating tables on Heroku.

**Comment by mnzube** [comment]
Hey Faustin, I found out the proper way of creating a link to the pivotal tracker number on the relevant tracker story question is as follows.
1. Paste the PT number.
2. Click the link icon on the top.
3. Then put in the link in the brackets that will be displayed after step 2.

**Review by Joe-Joseph — COMMENTED** [review]
Good job Faustin, now the tables are created on Heroku

**Pull request merged**
