### PR TITLE
#166790082 implementing swagger configuration

### PR DESCRIPTION
**Pull request by mnzube**
#### What does this PR do?
This PR adds swagger configuration to Authors Haven Jawans dev app
#### Description of Task to be completed?
Add swagger.json file and swagger express documentation
#### How should this be manually tested?
Run npm start then paste the following link http://localhost:3000/api-docs/
#### Any background context you want to provide?
n/a
#### What are the relevant pivotal tracker stories?
[166790082](https://www.pivotaltracker.com/story/show/166790082)
#### Screenshots (if appropriate)
Screenshot 2019-06-26 at 12 15 04

#### Questions:

### CODE REVIEW

**Comment by kipropbrian** [comment]
The following is not formatted properly. 

 - What are the relevant pivotal tracker stories?  [166790082]
 -  Your PR title

**Review by pngabo — COMMENTED** [review]
I think you should detail in PR description how to test this.

**Comment by shaluchandwani** [comment]
Please change the PR description according to the format.

**Comment by FlevianK** [comment]
Nice reviews

**Pull request merged**
